[package]
name = "rproxy"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
reqwest = "0.12.22"
serde = { version = "1.0.219", features=["derive"] }
serde_json = "1.0.141"
tracing = "0.1.41"

