[package]
name = "rproxy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.40"
anyhow = "1.0.71"
futures = "0.3.31"
tokio-util = "0.7.15"
maplit = "1.0.2"
tokio = { version = "1.28.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
